sprite $cisco_ldap [100x90/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCBCCCCCFCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFCCCCCCCCCCCCBCFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFCCCCCCCCCCCCCCFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBCCCCCBFFFCCCCCCCCCCCCCCFFCCCCCFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFCCCCCCCCCCCCCCFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFCCCCCCCCCCCCCFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCACCFFFFFCCCCCCCCCCCCFFFFFCCCCCCBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFCCCCCCCCCCFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFCCCCCCCFFFFFFFFFCCCCCBCBFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFCCCCCCCFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFCCCCCCCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFCCDCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFCECCCCCCFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFCCCCCCCCCCCCCCBCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFCCCCCCCCBCCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCECCCFFFFFFFCCCCCCCCFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFCCCCFCCCCCCCCCCCFFFFCCCCCCCCCCCCCCCCFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFCCCCCCCCCCCCCCCCFFFFFFCCBCCCCCCCCCCCCCFFFFCCCCCCCCFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCCCFFFFFCCCCCCCCFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFCCCCCCCCFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFCCCCCBCCFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFCCCCCCCCFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFCCCCCCCCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCDCCFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFCCCCCCCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFCCCCCCCBFFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define CISCO_LDAP(_color)                                 SPRITE_PUT(                              cisco_ldap, _color)
!define CISCO_LDAP(_color, _scale)                         SPRITE_PUT(                              cisco_ldap, _color, _scale)
!define CISCO_LDAP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, CISCO LDAP,         cisco_ldap, _color, _scale)
!define CISCO_LDAP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, CISCO LDAP,         cisco_ldap, _color, _scale, _shape)
!define CISCO_LDAP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, CISCO LDAP, _label, cisco_ldap, _color, _scale, _shape)
skinparam folderBackgroundColor<<CISCO LDAP>> White
