sprite $cisco_lock [100x100/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCECCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCBCFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFCCCCCCCCCCCFFCCCCCCCCCCCFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFCCCCCCCCCFFFFFFCCCCCCCCCCFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFCCCCCCCCCFFFFFFFFCCCCCCCCCFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFC4CCCCCCCFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFCCCCCCCFFFFFFFFFFFFFFFCCCCCCCDCFFFFFFFFFFFF
FFFFFFFFFFFFFECCCCCCCCFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCDFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFCCCCCCCCCCFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFCCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFCCCCCCCCCCFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFCCCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCCFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFCCCCCCCCCCFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCCFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCCCCCCFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFCCCCCCCCCCFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCCCCCCFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFCCCCCCCCCCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCCCCCCCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFCCCCCCCCCCBFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFCCCCCCCCCCCFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFCCCCCCCCCCCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFCCCCCCCCCCCCFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFCCCCCCCCCCCFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFCCCCCCCCCCCCFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFBCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFC9CCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFCCCBCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCC8CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCECCCCCCCCCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define CISCO_LOCK(_color)                                 SPRITE_PUT(                              cisco_lock, _color)
!define CISCO_LOCK(_color, _scale)                         SPRITE_PUT(                              cisco_lock, _color, _scale)
!define CISCO_LOCK(_color, _scale, _alias)                 SPRITE_ENT(  _alias, CISCO LOCK,         cisco_lock, _color, _scale)
!define CISCO_LOCK(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, CISCO LOCK,         cisco_lock, _color, _scale, _shape)
!define CISCO_LOCK(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, CISCO LOCK, _label, cisco_lock, _color, _scale, _shape)
skinparam folderBackgroundColor<<CISCO LOCK>> White
